### PR TITLE
Removing usage of busybox image to add Jaeger

### PR DESCRIPTION
**Pull request by dileepng**
*Issue #, if available:*

*Description of changes:*
Removing the usage of busybox image when we want to use Jaeger tracing because with newer App Mesh envoy images the configuration will be generated by itself.

related issue: [more information ](https://github.com/aws/aws-app-mesh-controller-for-k8s/issues/619)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by EdwardXF — APPROVED** [review]

**Comment by suniltheta** [comment]
I see only change related to removing Jaeger config. Is there a change where we don't include busybox sidecar?

**Review by suniltheta — APPROVED** [review]

**Comment by dileepng** [comment]
> I see only change related to removing Jaeger config. Is there a change where we don't include busybox sidecar?

busbox image is in initCointainer, which generates configuration for Jaeger tracer. so removed that initContainer.

**Comment by BennettJames** [comment]
What versions of envoy is this change compatible with? We should probably announce a envoy version floor as part of the next release if this will be incompatible with older versions.

**Comment by dileepng** [comment]
since from envoy version v1.16.1.0 this change is compatible with this configuration.

**Pull request merged**
