### PR TITLE
bump to apiextensions v1

### PR DESCRIPTION
**Pull request by allamand**
Signed-off-by: Sebastien Allamand <sallaman@amazon.com>

*Issue #, if available:* #491

*Description of changes:*

Upgrade from `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1`

I wonder however how to upgrade helm chart for using the new CRD and to which version ? appreciate some help here.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cgchinmay** [comment]
Hi @allamand 
We noticed that this is a breaking change as v1 doesn't preserve unknown fields in the CRD. So we need to update CRD's to have preserve unknown field annotation.

**Review by cgchinmay — CHANGES_REQUESTED** [review]
Need to resolve merge conflicts

**Comment by Shreya027** [comment]
Hi, I think this PR also needs to take into consideration preservation of unknown fields that get dropped in CRD version v1. 

If you try adding preserveUnknownFields=true in the CRD_OPTIONS as shown below:

CRD_OPTIONS?="crd:trivialVersions=true,crdVersions=v1beta1,preserveUnknownFields=true" and apply the changes, you get the following error in the terminal:

                __you may only set PreserveUnknownFields to true with v1beta1 CRDs
                Error: not all generators ran successfully__
                
I figured out one option can be using` // +kubebuilder:pruning:PreserveUnknownFields` on top of type structs to preserve fields.

**Comment by cgchinmay** [comment]
Closing this PR as we are tracking it here: https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/562

**Pull request closed without merging**
