### PR TITLE
Update PodDisruptionBudget API version for Kubernetes 1.25

### PR DESCRIPTION
**Pull request by igreg**
*Issue #, if available:*

*Description of changes:*

The Beta API version (policy/v1beta1) of PodDisruptionBudget is no longer served as of version 1.25.
cf. https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-25

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by igreg** [comment]
I am taking over PR #723 which had outstanding comments that had not been resolved. I am currently blocked and unable to deploy the `appmesh-controller` to an EKS cluster upgraded to 1.25.

**Comment by igreg** [comment]
@BennettJames Would you be able to help with this PR? I saw you commented on the PR I'm taking over.

**Review by BennettJames — APPROVED** [review]

**Comment by BennettJames** [comment]
Hey Greg,

This looks good; I added an appoval. I'll merge it once the build succeeds.

**Comment by igreg** [comment]
Thanks @BennettJames. Sorry, I merged the master into the PR after the build (which was green) believing this would help but didn't realize the workflows were also requiring approval so it's awaiting your approval again.

**Pull request merged**
