### PR TITLE
Update walkthroughs links to main branch

### PR DESCRIPTION
**Pull request by Y0Username**
*Description of changes:*
Fixing walkthrough links

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by suniltheta** [comment]
You can probably update here as well https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/config/helm/appmesh-controller/README.md?plain=1

**Review by cgchinmay — APPROVED** [review]

**Comment by cgchinmay** [comment]
Will wait for @Y0Username to update the controller readme as well

**Comment by Y0Username** [comment]
@cgchinmay I was not watching this, did not see the comment. Updated the PR.

**Comment by cgchinmay** [comment]
> @cgchinmay I was not watching this, did not see the comment. Updated the PR.

@Y0Username Could you update the branch ? it has got out of sync

**Pull request merged**
