### PR TITLE
Bump Envoy image version to v1.18.3.0-prod

### PR DESCRIPTION
**Pull request by shwetasahuit**
Description of changes:
Bump AppMesh Envoy image version from v1.17.2.0-prod to v1.18.3.0-prod

Envoy v1.18.3 release notes for reference: https://www.envoyproxy.io/docs/envoy/v1.18.3/version_history/current

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cgchinmay** [comment]
@shwetasahuit were there any tests performed for this image upgrade ? Asking for future image upgrades as well, would help. Thanks

**Comment by shwetasahuit** [comment]
Yes we run multiple tests to verify the validity of the envoy image. These tests are part of our code pipeline.

**Comment by cgchinmay** [comment]
> Yes we run multiple tests to verify the validity of the envoy image. These tests are part of our code pipeline.

Hi, We also need to run e2e controller test with by building a controller image using this new envoy image. Only after that we can merge this PR. 

Here are the steps, to be run from the aws-appmesh-controller directory 
```
make all 

# build controller image
docker build -t amazon/appmesh-controller .

# deploy controller in your cluster using this new image
helm upgrade -i appmesh-controller eks/appmesh-controller \
    --namespace appmesh-system \
    --set region=$AWS_REGION \
    --set serviceAccount.create=false \
    --set serviceAccount.name=appmesh-controller \
    --set image.repository=<your repo name for the image> --set image.tag=<tag>

# Run ginkgo suite for e2e tests
ginkgo -v -r test/e2e -- --cluster-kubeconfig=<absolute path to your kube config file> --cluster-name=<cluster name>--aws-region=$AWS_REGION --aws-vpc-id=<VPC ID of your cluster>
```

**Comment by suniltheta** [comment]
Closing in favor of #505 v1.19.1.0-prod

**Pull request closed without merging**
