### PR TITLE
Update proxy route manager to v4-prod

### PR DESCRIPTION
**Pull request by suniltheta**
**Description of changes:**
Update Default App Mesh Proxy Route Manager Image version to v4-prod

**Testing**
Ran eks walkthrough howto-k8s-http2 to confirm the working of this image.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cgchinmay** [comment]
> Update Default App Mesh Proxy Route Manager Image version to v3-prod to fix above issue

Which issue ?

**Comment by suniltheta** [comment]
Fixed the description.

**Comment by cgchinmay** [comment]
Validated e2e and integration tests. All Passed

**Review by cgchinmay — APPROVED** [review]
lgtm

**Pull request merged**
