### PR TITLE
Volume injection support

### PR DESCRIPTION
**Pull request by ameir**
*Issue #, if available:* N/A

*Description of changes:*
This PR adds support for mounting a volume specified in your pod manifest into the Envoy sidecar. This obviates the need for a custom image build for file-based certificates.

Background: we have an agent that rotates certificates daily, so using the secrets mount solution is not practical. This agent runs on each worker node, but there is also a sidecar that can run with this agent to mint certificates with an identity specific to the app. Whichever the approach, the agent talks to a service that issues these certificates, signed by our CA. 

Because the rotation happens automatically (and at random times), it is not practical to have another process watching for filesystem changes, update the secrets mount, and reload Envoy (if necessary). The vast majority of our applications are using this sidecar approach, each with a different identity, so all of the certificates across the cluster are unique.

With the `certificateChain` and `privateKey` options, the paths are relative to `/` in the Envoy sidecar. If not using `secretsMount`, then a custom image must be made to pull the certificates on startup, unless they are baked in. This solution allows for certificates to be mounted from a volume to avoid these workarounds. A sidecar could do the certificate pull/rotation, and have them available to Envoy immediately. 

Example showing `/var/lib/sia` being mounted from the worker node to the Envoy sidecar via `volumeMounts`:

```
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: fleks-vn
  namespace: fleks
spec:
  podSelector:
    matchLabels:
      app: default-behavior

  backendDefaults:
    clientPolicy:
      tls:
        certificate:
          file:
            certificateChain: /var/lib/sia/certs/service.cert.pem
            privateKey: /var/lib/sia/keys/service.key.pem
        enforce: true
        ports: []
        validation:
          trust:
            file:
              certificateChain: /var/lib/sia/certs/ca.cert.pem

  listeners:
    - portMapping:
        port: 8080
        protocol: http

      tls:
        mode: STRICT
        certificate:
          file:
            certificateChain: /var/lib/sia/certs/service.cert.pem
            privateKey: /var/lib/sia/keys/service.key.pem
        validation:
          trust:
            file:
              certificateChain: /var/lib/sia/certs/ca.cert.pem

  logging: {}
  serviceDiscovery:
    dns:
      hostname: default-behavior.fleks.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-behavior
  namespace: fleks
spec:
  selector:
    matchLabels:
      app: default-behavior
  template:
    metadata:
      labels:
        app: default-behavior
      annotations:
        appmesh.k8s.aws/volumeMounts: sia:/var/lib/sia
        appmesh.k8s.aws/sidecarInjectorWebhook: enabled
    spec:
      containers:
      - name: default-behavior
        image: k8s.gcr.io/echoserver:1.4
        volumeMounts:
        - mountPath: /var/lib/sia
          name: sia
      volumes:
      - name: sia
        hostPath:
          path: /var/lib/sia
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by rajal-amzn — COMMENTED** [review]
Changes look good to me. Will let Chinmay validate as well before merging.

**Comment by cgchinmay** [comment]
@ameir Could you add a UT as well ?

**Review by cgchinmay — CHANGES_REQUESTED** [review]
Would be great if you can add some UT for the test scenario

**Comment by ameir** [comment]
Thanks, @cgchinmay; I've just updated this PR as requested. Please let me know if you have any other feedback.

**Review by cgchinmay — APPROVED** [review]

**Comment by cgchinmay** [comment]
> Thanks, @cgchinmay; I've just updated this PR as requested. Please let me know if you have any other feedback.

lgtm, but for my understanding and someone else, could you add explain little more in your PR description on how this helps in certificate rotation. And why was the secret mount a problem ?  Thanks

**Review by cgchinmay — CHANGES_REQUESTED** [review]
Add more info to the PR description

**Comment by ameir** [comment]
@cgchinmay I've just updated the PR description; please let me know if you need any additional detail.

**Comment by cgchinmay** [comment]
> @cgchinmay I've just updated the PR description; please let me know if you need any additional detail.

Thank you. approved

**Review by cgchinmay — APPROVED** [review]

**Comment by ameir** [comment]
Thanks, @cgchinmay, for reviewing and approving. Do you have an idea of when this may be released? We're currently using a custom image in the meantime, but would love to switch to an official image whenever possible. Thanks for your support!

**Comment by cgchinmay** [comment]
@ameir It should be within (~1-2 weeks), will update you once I have exact date.

**Comment by cgchinmay** [comment]
> @ameir It should be within (~1-2 weeks), will update you once I have exact date.

Apologies for the delay. It's been tracked in v1.4.2 release of controller and will be released soon.

**Pull request merged**
